chore: rewrite workflow

diff --git a/.github/workflows/changelog.yaml b/.github/workflows/changelog.yaml
--- a/.github/workflows/changelog.yaml
+++ b/.github/workflows/changelog.yaml
@@ -3,18 +3,26 @@ name: changelog entry
 on:
   pull_request:
     types: [opened, synchronize, labeled, unlabeled, reopened]
+    branches:
+      - master
 
 permissions:
   contents: read
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   check-changelog-entry:
     name: Check for changelog entry
     runs-on: ubuntu-latest
+    if: contains(github.event.pull_request.labels.*.name, 'skip news') != true
+
     steps:
       - uses: actions/checkout@v3
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
+          # towncrier needs a non-shallow clone
           fetch-depth: '0'
 
       - name: Set up environment
@@ -23,14 +31,13 @@ jobs:
           python-version: '3.9'
           nox-setup: "tools"
 
-      - run: python -m pip install towncrier
-
       - name: Check for presence of a Change Log fragment (only pull requests)
-        if: contains(github.event.pull_request.labels.*.name, 'skip news') != true
         # NOTE: The pull request' base branch needs to be fetched so towncrier
         # is able to compare the current branch with the base branch.
         run: |
-          git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
-          towncrier check --compare-with origin/${BASE_BRANCH}
+          if ! towncrier check --compare-with origin/${BASE_BRANCH}; then
+            echo "::error::Please see https://github.com/DisnakeDev/disnake/blob/master/changelog/README.rst for details on how to create a changelog entry." >&2
+            exit 1
+          fi
         env:
           BASE_BRANCH: ${{ github.base_ref }}
