test: add coveralls reporting

diff --git a/.github/workflows/lint-test.yml b/.github/workflows/lint-test.yml
--- a/.github/workflows/lint-test.yml
+++ b/.github/workflows/lint-test.yml
@@ -154,14 +154,59 @@ jobs:
 
     - name: Install requirements
       run: |
-        python -m pip install nox
+        python -m pip install nox coveralls==3.3.1 coverage[toml]~=6.3.2
 
     - name: Test package install
       run: |
         python -m pip install .
 
     - name: Run pytest
+      id: run_tests
       # use non-utc timezone, to test time/date-dependent features properly
       env:
         TZ: "America/New_York"
-      run: nox -s test-${{ matrix.python-version }}
+      run: |
+        echo '```' >> $GITHUB_STEP_SUMMARY
+        nox -s test-${{ matrix.python-version }} -- --color=no >> $GITHUB_STEP_SUMMARY
+        echo '```' >> $GITHUB_STEP_SUMMARY
+
+
+    # This step will publish the coverage reports to coveralls.io and
+    # print a "job" link in the output of the GitHub Action
+    - name: Publish coverage report to coveralls.io
+      # upload coverage even if a test run failed
+      # this is a test, and may be removed in the future
+      if: always() && (steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure')
+      # important that we don't fail the workflow when coveralls is down
+      continue-on-error: true
+      env:
+        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        COVERALLS_FLAG_NAME: coverage-${{ runner.os }}-python-${{ env.PYTHON_VERSION }}
+        COVERALLS_PARALLEL: true
+        COVERALLS_SERVICE_NAME: github
+      run: python -m coveralls
+
+  coveralls-finish:
+    name: Indicate completion to coveralls.io
+    runs-on: ubuntu-latest
+    needs: pytest
+    # we don't want to fail the workflow when coveralls is down
+    continue-on-error: true
+    # as long as the tests were ran, we want to send a finish to coveralls
+    if: success() || failure()
+    steps:
+      # Set up a consistent version of Python
+    - name: Set up Python 3.9
+      id: python
+      uses: actions/setup-python@v3
+      with:
+        python-version: '3.9'
+
+    - name: Coveralls Finished
+      continue-on-error: true
+      env:
+        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        COVERALLS_SERVICE_NAME: github
+      run: |
+        python3 -m pip install --upgrade coveralls
+        python3 -m coveralls --finish
